// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNwrsu9xclbzJ0E1pzL8YwujVZ4yC44eE',
    appId: '1:540377633798:web:c5e032fe7dceaeaa101f87',
    messagingSenderId: '540377633798',
    projectId: 'flutter-learn-96e22',
    authDomain: 'flutter-learn-96e22.firebaseapp.com',
    storageBucket: 'flutter-learn-96e22.appspot.com',
    measurementId: 'G-53Y94761WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCLKUuJM2hJugNTE5q1RGoXVldoxvf9k',
    appId: '1:540377633798:android:2668ded06e4fb73e101f87',
    messagingSenderId: '540377633798',
    projectId: 'flutter-learn-96e22',
    storageBucket: 'flutter-learn-96e22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFPEWggdmWdFRxZa2A1ytBHbjKSf-Hn_U',
    appId: '1:540377633798:ios:5268ccba3b7ecd8b101f87',
    messagingSenderId: '540377633798',
    projectId: 'flutter-learn-96e22',
    storageBucket: 'flutter-learn-96e22.appspot.com',
    iosBundleId: 'com.example.flutterLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFPEWggdmWdFRxZa2A1ytBHbjKSf-Hn_U',
    appId: '1:540377633798:ios:406f589bc398ce15101f87',
    messagingSenderId: '540377633798',
    projectId: 'flutter-learn-96e22',
    storageBucket: 'flutter-learn-96e22.appspot.com',
    iosBundleId: 'com.example.flutterLearn.RunnerTests',
  );
}
